$axure.loadCurrentPage({
  "url":"login.html",
  "generationDate":new Date(1486558029647.81),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"77da7ba76ffe421c97140f6dba8f24f4",
    "type":"Axure:Page",
    "name":"Login",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"80f31e8e5f784102aaa201b1b37b0934",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"44eb6ab415ff46fd83a9526232f2c956"},
{
          "id":"75452e7b66984923b5f7a8b0afc22a26",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF16A2DE},
            "location":{
              "x":436,
              "y":240},
            "size":{
              "width":330,
              "height":180},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b19a6601ddb44e18878c88eacf497616",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF16A2DE},
                "location":{
                  "x":436,
                  "y":240},
                "size":{
                  "width":330,
                  "height":180},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u3.png"}},
{
          "id":"88bd79c35f244f458d54ad9a8a43fc65",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0075A2,
              "opacity":1},
            "location":{
              "x":546,
              "y":277},
            "size":{
              "width":185,
              "height":26},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76c5783702f44fe7b67bead9b419a718",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0075A2,
                  "opacity":1},
                "location":{
                  "x":546,
                  "y":277},
                "size":{
                  "width":185,
                  "height":26},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"a229df1197bd441d9e8e262d820a7756",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":470,
              "y":283},
            "size":{
              "width":63,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc5d933eadfc4bc780bfb05f94be6ea7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":283},
                "size":{
                  "width":63,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8d1b2ee07e24e32894711036ab2d440",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0075A2,
              "opacity":1},
            "location":{
              "x":546,
              "y":317},
            "size":{
              "width":185,
              "height":26},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b459109843d746b9b743a991cf99615f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0075A2,
                  "opacity":1},
                "location":{
                  "x":546,
                  "y":317},
                "size":{
                  "width":185,
                  "height":26},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u5.png"}},
{
          "id":"443169eba96941c2a1832bfc0cef8bf7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":470,
              "y":323},
            "size":{
              "width":62,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"97b54a0164084bbf86acdd0dcbffd055",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":470,
                  "y":323},
                "size":{
                  "width":62,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5bad348fdf614afe8e81d9b7720646f4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFE4E4E4},
            "location":{
              "x":501,
              "y":70},
            "size":{
              "width":200,
              "height":90},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d972ae9630a94d228fbc19f4f5e5ea1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4},
                "location":{
                  "x":501,
                  "y":70},
                "size":{
                  "width":200,
                  "height":90},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u13.png"}},
{
          "id":"3b5d814ae0214ed396fbe82b79693b60",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":562,
              "y":476},
            "size":{
              "width":82,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46f3bbcf69c24589a965a931a5e865ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":562,
                  "y":476},
                "size":{
                  "width":82,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c8d59403ae4343febba0b396c532a618",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "fill":{
              "fillType":"solid",
              "color":0xFFE6E6E7},
            "location":{
              "x":661,
              "y":364},
            "size":{
              "width":70,
              "height":26},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "cornerRadiusTopLeft":"2"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d13d9b46631473c8a402dc597309ac6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE6E6E7},
                "location":{
                  "x":661,
                  "y":364},
                "size":{
                  "width":70,
                  "height":26},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "cornerRadiusTopLeft":"2"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u17.png"}},
{
          "id":"a26ab5c3dcfb4eb396a8bd8e7438df87",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF16A2DE,
              "opacity":1},
            "location":{
              "x":567,
              "y":570},
            "size":{
              "width":69,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dc25e94829b4a17ab8c4a7191b201e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF16A2DE,
                  "opacity":1},
                "location":{
                  "x":567,
                  "y":570},
                "size":{
                  "width":69,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ccda315c7584dfeaa1a6b47a641aecb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":511,
              "y":591},
            "size":{
              "width":200,
              "height":34}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"05dc08ace3d240e1b05c0e9ea5938274",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":511,
                  "y":591},
                "size":{
                  "width":200,
                  "height":34}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/login/u21.png"}}]}},
  "masters":{
    "44eb6ab415ff46fd83a9526232f2c956":{
      "packageId":"44eb6ab415ff46fd83a9526232f2c956",
      "type":"Axure:Master",
      "name":"login",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"bf71a422ea1f40698297525ae0d194ca",
            "label":"",
            "type":"buttonShape",
            "styleType":"buttonShape",
            "visible":true,
            "style":{
              "fill":{
                "fillType":"solid",
                "color":0xFFF1F1F1},
              "size":{
                "width":1200,
                "height":690},
              "borderFill":{
                "fillType":"solid",
                "color":0xFFCCCCCC}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1cb6c79e988042ea8e3fa5c3cbca1e69",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "fill":{
                    "fillType":"solid",
                    "color":0xFFF1F1F1},
                  "size":{
                    "width":1200,
                    "height":690},
                  "borderFill":{
                    "fillType":"solid",
                    "color":0xFFCCCCCC}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/login/u1.png"}}]}}},
  "objectPaths":{
    "80f31e8e5f784102aaa201b1b37b0934":{
      "scriptId":"u0",
      "bf71a422ea1f40698297525ae0d194ca":{
        "scriptId":"u1"},
      "1cb6c79e988042ea8e3fa5c3cbca1e69":{
        "scriptId":"u2"}},
    "75452e7b66984923b5f7a8b0afc22a26":{
      "scriptId":"u3"},
    "b19a6601ddb44e18878c88eacf497616":{
      "scriptId":"u4"},
    "88bd79c35f244f458d54ad9a8a43fc65":{
      "scriptId":"u5"},
    "76c5783702f44fe7b67bead9b419a718":{
      "scriptId":"u6"},
    "a229df1197bd441d9e8e262d820a7756":{
      "scriptId":"u7"},
    "fc5d933eadfc4bc780bfb05f94be6ea7":{
      "scriptId":"u8"},
    "c8d1b2ee07e24e32894711036ab2d440":{
      "scriptId":"u9"},
    "b459109843d746b9b743a991cf99615f":{
      "scriptId":"u10"},
    "443169eba96941c2a1832bfc0cef8bf7":{
      "scriptId":"u11"},
    "97b54a0164084bbf86acdd0dcbffd055":{
      "scriptId":"u12"},
    "5bad348fdf614afe8e81d9b7720646f4":{
      "scriptId":"u13"},
    "d972ae9630a94d228fbc19f4f5e5ea1d":{
      "scriptId":"u14"},
    "3b5d814ae0214ed396fbe82b79693b60":{
      "scriptId":"u15"},
    "46f3bbcf69c24589a965a931a5e865ac":{
      "scriptId":"u16"},
    "c8d59403ae4343febba0b396c532a618":{
      "scriptId":"u17"},
    "2d13d9b46631473c8a402dc597309ac6":{
      "scriptId":"u18"},
    "a26ab5c3dcfb4eb396a8bd8e7438df87":{
      "scriptId":"u19"},
    "9dc25e94829b4a17ab8c4a7191b201e4":{
      "scriptId":"u20"},
    "9ccda315c7584dfeaa1a6b47a641aecb":{
      "scriptId":"u21"},
    "05dc08ace3d240e1b05c0e9ea5938274":{
      "scriptId":"u22"}}});